simplify run

diff --git a/hello/run b/hello/run
--- a/hello/run
+++ b/hello/run
@@ -1,7 +1,20 @@
 #!/bin/bash
 
-# my process id (to kill on error)
-export run_pid=$$
+# set process id to kill on error
+if [ -z "${err_pid+x}" ]
+then
+    export err_pid=$$
+fi
+
+# print error and die
+err() {
+    if [ $# -gt 0 ]
+    then
+	>&2 echo "$@"
+    fi
+    kill -SIGTERM $err_pid
+}
+export -f err
 
 # directory (absolute path) of this run script
 here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
@@ -13,15 +26,6 @@ tag="${tag// /_}"
 # bash cleanup
 cleanup() {
     docker stop $id
-}
-
-# print error and die
-err() {
-    if [ $# -gt 0 ]
-    then
-	>&2 echo "$@"
-    fi
-    kill -SIGTERM $run_pid
 }
 
 # build container or exit with failure
