better run

diff --git a/hello/run b/hello/run
--- a/hello/run
+++ b/hello/run
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# my process id (to kill on error)
+export run_pid=$$
+
 # directory (absolute path) of this run script
 here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
@@ -12,26 +15,32 @@ cleanup() {
     docker stop $id
 }
 
+# print error and die
+err() {
+    if [ $# -gt 0 ]
+    then
+	>&2 echo "$@"
+    fi
+    kill -SIGTERM $run_pid
+}
+
 # build container or exit with failure
-if ! docker build -t $tag .
+docker build -t $tag . || err "build $tag in '$here' failed."
+
+if [ $# -eq 0 ]
 then
-    echo "build $tag in '$here' failed." &>2
-    exit 1
+    # run container in background
+    id=$(docker run --detach --user user -it --rm -v "$(pwd):/app" $tag)
+    [ $? -eq  0 ] || err "run $tag in '$here' failed."
+
+    # make sure we clean up running container
+    trap cleanup SIGINT SIGTERM EXIT
+
+    # show output of container (output of continuous testing)
+    docker logs -f $id &
+
+    # log into container
+    docker exec -it $id bash -i
+else
+    docker run --user user -it --rm -v "$(pwd):/app" $tag "$@"
 fi
-
-# run container in background
-id=$(docker run --detach --user user -it --rm -v "$(pwd):/app" $tag)
-if [ $? -ne 0 ]
-then
-    echo "run $tag in '$here' failed." &>2
-    exit 1
-fi
-
-# make sure we clean up running container
-trap cleanup SIGINT SIGTERM EXIT
-
-# show output of container (output of continuous testing)
-docker logs -f $id &
-
-# log into container or run specific command
-docker exec -it $id bash -i
